#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time: 2020/6/5 15:37
# @Author: zhc
import pytest,allure
import requests

host = "http://103.131.171.121:9999"

def login(user,pwd):
    """登录"""
    login_url = host + '/authorization-server/oauth/token'
    header = {
        "Authorization": "Basic dGVzdF9jbGllbnQ6dGVzdF9zZWNyZXQ="
    }
    params = {
        "scope": "read",
        "grant_type": "password",
        "username": user,
        "password": pwd
    }
    res = requests.post(login_url, data=params, headers=header)
    try:
        return_type = res.json()["token_type"]
    except:
        print("大兄弟，报错了, 你看他返回的是啥：\n %s" % res.text)
        return_type = ''
    return return_type

test_datas = [
    ({"user": "zhcpc6", "pwd": "Password888"}, "bearer"),
    ({"user": "tyypc5", "pwd": "Password888"}, "bearer"),
    ({"user": "zhcpc8", "pwd": "Password888"}, "bearer"),
]

@allure.story("登录用例")
@pytest.mark.parametrize("test_input,expected",test_datas)
def test_login(test_input,expected):
    """测试登录用例"""
    result = login(test_input["user"],test_input["pwd"])
    assert result == expected

"""
生成xml报告,allure generate report/result_allure -o report/allure_html
生成html报告(前提:必需先生成xml报告)
allure generate report/result_allure -o report/allure_html

"""

